package com.compomics.traml.gui.forms;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

/**
 * This class is a
 */
public class ColumnPanel {
    private JLabel lblColumnHeader;
    private JLabel lblDescription;
    private JComboBox cmpColumnTypes;
    private JPanel jpanContent;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpanContent = new JPanel();
        jpanContent.setLayout(new FormLayout("right:100px:noGrow,left:4dlu:noGrow,fill:200px:noGrow,left:4dlu:noGrow,left:max(d;4px):grow", "center:d:grow"));
        cmpColumnTypes = new JComboBox();
        CellConstraints cc = new CellConstraints();
        jpanContent.add(cmpColumnTypes, cc.xy(3, 1));
        lblDescription = new JLabel();
        lblDescription.setText("Label");
        jpanContent.add(lblDescription, cc.xy(5, 1));
        lblColumnHeader = new JLabel();
        lblColumnHeader.setText("Label");
        jpanContent.add(lblColumnHeader, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanContent;
    }
}
