//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 04:21:17 PM PST 
//


package org.hupo.psi.ms.traml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of insutrument configurations used in the validation or optimization of the transitions
 * <p/>
 * <p>Java class for ConfigurationListType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ConfigurationListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Configuration" type="{http://psi.hupo.org/ms/traml}ConfigurationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationListType", propOrder = {
        "configuration"
})
public class ConfigurationListType {

    @XmlElement(name = "Configuration", required = true)
    protected ConfigurationType configuration;

    /**
     * Gets the value of the configuration property.
     *
     * @return possible object is
     *         {@link ConfigurationType }
     */
    public ConfigurationType getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     *
     * @param value allowed object is
     *              {@link ConfigurationType }
     */
    public void setConfiguration(ConfigurationType value) {
        this.configuration = value;
    }

}
