//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 02:09:45 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/ms/traml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hupo.psi.ms.traml;
