//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 04:21:17 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/ms/traml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package org.hupo.psi.ms.traml;
