package com.compomics.traml.gui.forms;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * This class is a
 */
public class SepToTRAML {


    private JPanel jpanContent;
    private JPanel jpanColumns;
    private JPanel jpanHead;
    private JPanel jpanBottom;
    private JButton btnTraml;
    private JButton btnOpen;
    private JButton btnTest;
    private JLabel lblFilename;


    /**
     * Constructs a new SepToTraml instance with a JPanel as a root component.
     */
    public SepToTRAML() {
        btnTraml.setBorder(new EmptyBorder(0, 0, 0, 0));

    }

    public static void main(String[] args) {
        JFrame lFrame = new JFrame("SepToTRAML");
        lFrame.setContentPane(new SepToTRAML().jpanContent);
        lFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lFrame.pack();
        lFrame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpanContent = new JPanel();
        jpanContent.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        jpanColumns = new JPanel();
        jpanColumns.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        jpanColumns.setBackground(new Color(-6684775));
        CellConstraints cc = new CellConstraints();
        jpanContent.add(jpanColumns, cc.xy(1, 3));
        jpanHead = new JPanel();
        jpanHead.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow", "center:d:noGrow"));
        jpanContent.add(jpanHead, cc.xy(1, 1));
        lblFilename = new JLabel();
        lblFilename.setFont(new Font(lblFilename.getFont().getName(), Font.ITALIC, 11));
        lblFilename.setText("Filename");
        jpanHead.add(lblFilename, cc.xy(3, 1));
        btnOpen = new JButton();
        btnOpen.setText("Open");
        jpanHead.add(btnOpen, cc.xy(1, 1));
        jpanBottom = new JPanel();
        jpanBottom.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):grow", "center:d:noGrow"));
        jpanContent.add(jpanBottom, cc.xy(1, 5));
        btnTest = new JButton();
        btnTest.setText("Test");
        jpanBottom.add(btnTest, cc.xy(1, 1));
        btnTraml = new JButton();
        btnTraml.setText("TraML");
        jpanBottom.add(btnTraml, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanContent;
    }
}
